### ISSUE TITLE
Simple way of being notified of ctrl-c signals

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/io#17]
Something like:

```dart
Stream<Null> get onTerminate => ...
```

Example use:

```dart
final server = await serve(...);
onTerminate.listen((_) => server.close());
```

**Comment by matanlurey** [comment]
Better than having to understand/dig through this:

https://stackoverflow.com/questions/18448306/how-to-catch-sigint-for-the-current-in-dart

**Comment by nex3** [comment]
Which signals would `onTerminate` recognize?

**Comment by matanlurey** [comment]
Probably a combination of SIGINT and a few others?

I imagine what a user really wants is (a) intentionally closed or (b) force closed (i.e. by `kill`).

```dart
onTerminate.listen((_) {
  _closeServer();
  _deleteTempFiles();
});
```

**Comment by nex3** [comment]
Can a process catch SIGKILL? If so, should it? I thought the point was to force the process to close without doing any additional work.

**Comment by matanlurey** [comment]
Probably not a high priority issue. Closing for now.
