### ISSUE TITLE
Add SDK path utilities

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/io#50]
See https://github.com/search?o=desc&p=2&q=org%3Adart-lang+%22+p.dirname%28p.dirname%28Platform.resolvedExecutable%29%29%22&s=indexed&type=Code

We copy this code A LOT!

**Comment by kevmoo** [comment]
So we've copied this code about a dozen times.

We have it in `package:cli_util` - https://pub.dev/documentation/cli_util/latest/cli_util/getSdkPath.html

I was thinking it'd be better to put here, since we use this package a bit more.

Thoughts @jakemac53 @natebosch @grouma ?

**Comment by kevmoo** [comment]
I was thinking of adding code to get access to the `pub` executable (with `.bat` on Windows, etc)

**Comment by natebosch** [comment]
It's hard to say, `cli_util` was a pain point for us and the fact that we haven't been using it points away from a solution like this. Bazel needs a different pattern than non-bazel, so we end up with a patch for bazel.

**Comment by jakemac53** [comment]
Ya we would end up with the same patch in multiple packages etc...

**Comment by grouma** [comment]
@natebosch I don't follow your argument. We patch `package:cli_util` internally for Google3. If we standardize on this package then it only needs to be patched once?

**Comment by natebosch** [comment]
I think we've patched differently in different places. I can't recall all of the details, I mostly remember being constantly annoyed by `cli_util`.

**Comment by kevmoo** [comment]
Ugh. I hate reinventing the wheel all over.

*sigh* okay
