### ISSUE TITLE
Common ANSI color utils?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/io#9]
CC @matanlurey 

We've reinvented these a dozen times...

The one we have internally [ansicolor](https://pub.dartlang.org/packages/ansicolor) is 4 years old

**Comment by matanlurey** [comment]
Sgtm! Send a PR?

**Comment by kevmoo** [comment]
QQ: I created a model for this where you actually created a `ShellString` object that you could concat, etc. – it also contains an option for an `alt` output to use if you don't want output with color.

Then at output time you could pass in a `bool` colorize or not and it does the right thing.

It's certainly heavier than just having a call to `wrap`, but it's gives more control over customizing the behavior.

The alternative: you pin off `!Platform.isWindows && stdioType(stdout) == StdioType.TERMINAL;`

**Comment by kevmoo** [comment]
Here's the code - https://github.com/kevmoo/bot_io.dart/blob/master/lib/src/shell_string.dart

**Comment by matanlurey** [comment]
My intuition is to offer something lighter - less of a chance of folks
spinning their own because ours is too heavy
